// WARNING: Please don't edit this file. It was generated by C++/WinRT v2.0.201026.4

#ifndef WINRT__02HelloWinRTApp_1_H
#define WINRT__02HelloWinRTApp_1_H
#include "winrt/impl/_02HelloWinRTApp.0.h"
WINRT_EXPORT namespace winrt::_02HelloWinRTApp
{
    struct __declspec(empty_bases) IMainPage :
        Windows::Foundation::IInspectable,
        impl::consume_t<IMainPage>
    {
        IMainPage(std::nullptr_t = nullptr) noexcept {}
        IMainPage(void* ptr, take_ownership_from_abi_t) noexcept : Windows::Foundation::IInspectable(ptr, take_ownership_from_abi) {}
    };
}
#endif
