// WARNING: Please don't edit this file. It was generated by C++/WinRT v2.0.201026.4

#ifndef WINRT__02HelloWinRTApp_0_H
#define WINRT__02HelloWinRTApp_0_H
WINRT_EXPORT namespace winrt::Windows::UI::Xaml::Markup
{
    struct IXamlMetadataProvider;
}
WINRT_EXPORT namespace winrt::_02HelloWinRTApp
{
    struct IMainPage;
    struct MainPage;
    struct XamlMetaDataProvider;
}
namespace winrt::impl
{
    template <> struct category<_02HelloWinRTApp::IMainPage>{ using type = interface_category; };
    template <> struct category<_02HelloWinRTApp::MainPage>{ using type = class_category; };
    template <> struct category<_02HelloWinRTApp::XamlMetaDataProvider>{ using type = class_category; };
    template <> inline constexpr auto& name_v<_02HelloWinRTApp::MainPage> = L"_02HelloWinRTApp.MainPage";
    template <> inline constexpr auto& name_v<_02HelloWinRTApp::XamlMetaDataProvider> = L"_02HelloWinRTApp.XamlMetaDataProvider";
    template <> inline constexpr auto& name_v<_02HelloWinRTApp::IMainPage> = L"_02HelloWinRTApp.IMainPage";
    template <> inline constexpr guid guid_v<_02HelloWinRTApp::IMainPage>{ 0xB47CE5D8,0xBC5C,0x53F9,{ 0xB7,0x2A,0x2A,0x66,0xE1,0x27,0x24,0xA1 } }; // B47CE5D8-BC5C-53F9-B72A-2A66E12724A1
    template <> struct default_interface<_02HelloWinRTApp::MainPage>{ using type = _02HelloWinRTApp::IMainPage; };
    template <> struct default_interface<_02HelloWinRTApp::XamlMetaDataProvider>{ using type = Windows::UI::Xaml::Markup::IXamlMetadataProvider; };
    template <> struct abi<_02HelloWinRTApp::IMainPage>
    {
        struct __declspec(novtable) type : inspectable_abi
        {
            virtual int32_t __stdcall get_MyProperty(int32_t*) noexcept = 0;
            virtual int32_t __stdcall put_MyProperty(int32_t) noexcept = 0;
        };
    };
    template <typename D>
    struct consume__02HelloWinRTApp_IMainPage
    {
        [[nodiscard]] WINRT_IMPL_AUTO(int32_t) MyProperty() const;
        WINRT_IMPL_AUTO(void) MyProperty(int32_t value) const;
    };
    template <> struct consume<_02HelloWinRTApp::IMainPage>
    {
        template <typename D> using type = consume__02HelloWinRTApp_IMainPage<D>;
    };
}
#endif
