// WARNING: Please don't edit this file. It was generated by C++/WinRT v2.0.201026.4

void* winrt_make__02HelloWinRTApp_MainPage()
{
    return winrt::detach_abi(winrt::make<winrt::_02HelloWinRTApp::factory_implementation::MainPage>());
}
WINRT_EXPORT namespace winrt::_02HelloWinRTApp
{
    MainPage::MainPage() :
        MainPage(make<_02HelloWinRTApp::implementation::MainPage>())
    {
    }
}
