// WARNING: Please don't edit this file. It was generated by C++/WinRT v2.0.201026.4

void* winrt_make__02HelloWinRTApp_XamlMetaDataProvider()
{
    return winrt::detach_abi(winrt::make<winrt::_02HelloWinRTApp::factory_implementation::XamlMetaDataProvider>());
}
WINRT_EXPORT namespace winrt::_02HelloWinRTApp
{
    XamlMetaDataProvider::XamlMetaDataProvider() :
        XamlMetaDataProvider(make<_02HelloWinRTApp::implementation::XamlMetaDataProvider>())
    {
    }
}
