// WARNING: Please don't edit this file. It was generated by C++/WinRT v2.0.201026.4

#pragma once
#include "winrt/Windows.UI.Xaml.Markup.h"
#include "winrt/_02HelloWinRTApp.h"
namespace winrt::_02HelloWinRTApp::implementation
{
    template <typename D, typename... I>
    struct __declspec(empty_bases) XamlMetaDataProvider_base : implements<D, _02HelloWinRTApp::XamlMetaDataProvider, I...>
    {
        using base_type = XamlMetaDataProvider_base;
        using class_type = _02HelloWinRTApp::XamlMetaDataProvider;
        using implements_type = typename XamlMetaDataProvider_base::implements_type;
        using implements_type::implements_type;
        
        hstring GetRuntimeClassName() const
        {
            return L"_02HelloWinRTApp.XamlMetaDataProvider";
        }
    };
}
namespace winrt::_02HelloWinRTApp::factory_implementation
{
    template <typename D, typename T, typename... I>
    struct __declspec(empty_bases) XamlMetaDataProviderT : implements<D, Windows::Foundation::IActivationFactory, I...>
    {
        using instance_type = _02HelloWinRTApp::XamlMetaDataProvider;

        hstring GetRuntimeClassName() const
        {
            return L"_02HelloWinRTApp.XamlMetaDataProvider";
        }
        auto ActivateInstance() const
        {
            return make<T>();
        }
    };
}

#if defined(WINRT_FORCE_INCLUDE_XAMLMETADATAPROVIDER_XAML_G_H) || __has_include("XamlMetaDataProvider.xaml.g.h")
#include "XamlMetaDataProvider.xaml.g.h"
#else

namespace winrt::_02HelloWinRTApp::implementation
{
    template <typename D, typename... I>
    using XamlMetaDataProviderT = XamlMetaDataProvider_base<D, I...>;
}

#endif
