// WARNING: Please don't edit this file. It was generated by C++/WinRT v2.0.190404.8

#ifndef WINRT_SDKTemplate_1_H
#define WINRT_SDKTemplate_1_H
#include "winrt/impl/SDKTemplate.0.h"
namespace winrt::SDKTemplate
{
    struct WINRT_EBO IMainPage :
        Windows::Foundation::IInspectable,
        impl::consume_t<IMainPage>
    {
        IMainPage(std::nullptr_t = nullptr) noexcept {}
        IMainPage(void* ptr, take_ownership_from_abi_t) noexcept : Windows::Foundation::IInspectable(ptr, take_ownership_from_abi) {}
    };
    struct WINRT_EBO IMainPageStatics :
        Windows::Foundation::IInspectable,
        impl::consume_t<IMainPageStatics>
    {
        IMainPageStatics(std::nullptr_t = nullptr) noexcept {}
        IMainPageStatics(void* ptr, take_ownership_from_abi_t) noexcept : Windows::Foundation::IInspectable(ptr, take_ownership_from_abi) {}
    };
    struct WINRT_EBO IScenario1_SecondaryWindow :
        Windows::Foundation::IInspectable,
        impl::consume_t<IScenario1_SecondaryWindow>
    {
        IScenario1_SecondaryWindow(std::nullptr_t = nullptr) noexcept {}
        IScenario1_SecondaryWindow(void* ptr, take_ownership_from_abi_t) noexcept : Windows::Foundation::IInspectable(ptr, take_ownership_from_abi) {}
    };
    struct WINRT_EBO IScenario2_DisplayRegion :
        Windows::Foundation::IInspectable,
        impl::consume_t<IScenario2_DisplayRegion>
    {
        IScenario2_DisplayRegion(std::nullptr_t = nullptr) noexcept {}
        IScenario2_DisplayRegion(void* ptr, take_ownership_from_abi_t) noexcept : Windows::Foundation::IInspectable(ptr, take_ownership_from_abi) {}
    };
    struct WINRT_EBO IScenario3_Size :
        Windows::Foundation::IInspectable,
        impl::consume_t<IScenario3_Size>
    {
        IScenario3_Size(std::nullptr_t = nullptr) noexcept {}
        IScenario3_Size(void* ptr, take_ownership_from_abi_t) noexcept : Windows::Foundation::IInspectable(ptr, take_ownership_from_abi) {}
    };
    struct WINRT_EBO IScenario4_CompactOverlay :
        Windows::Foundation::IInspectable,
        impl::consume_t<IScenario4_CompactOverlay>
    {
        IScenario4_CompactOverlay(std::nullptr_t = nullptr) noexcept {}
        IScenario4_CompactOverlay(void* ptr, take_ownership_from_abi_t) noexcept : Windows::Foundation::IInspectable(ptr, take_ownership_from_abi) {}
    };
    struct WINRT_EBO IScenario5_RelativePositioning :
        Windows::Foundation::IInspectable,
        impl::consume_t<IScenario5_RelativePositioning>
    {
        IScenario5_RelativePositioning(std::nullptr_t = nullptr) noexcept {}
        IScenario5_RelativePositioning(void* ptr, take_ownership_from_abi_t) noexcept : Windows::Foundation::IInspectable(ptr, take_ownership_from_abi) {}
    };
    struct WINRT_EBO ISecondaryAppWindowPage :
        Windows::Foundation::IInspectable,
        impl::consume_t<ISecondaryAppWindowPage>
    {
        ISecondaryAppWindowPage(std::nullptr_t = nullptr) noexcept {}
        ISecondaryAppWindowPage(void* ptr, take_ownership_from_abi_t) noexcept : Windows::Foundation::IInspectable(ptr, take_ownership_from_abi) {}
    };
}
#endif
