// WARNING: Please don't edit this file. It was generated by C++/WinRT v2.0.190404.8

#ifndef WINRT_Windows_Data_Html_2_H
#define WINRT_Windows_Data_Html_2_H
#include "winrt/impl/Windows.Data.Html.1.h"
namespace winrt::Windows::Data::Html
{
    struct HtmlUtilities
    {
        HtmlUtilities() = delete;
        static hstring ConvertToText(param::hstring const& html);
    };
}
#endif
