// WARNING: Please don't edit this file. It was generated by C++/WinRT v2.0.190404.8

#ifndef WINRT_Windows_Phone_ApplicationModel_2_H
#define WINRT_Windows_Phone_ApplicationModel_2_H
#include "winrt/impl/Windows.Phone.ApplicationModel.1.h"
namespace winrt::Windows::Phone::ApplicationModel
{
    struct ApplicationProfile
    {
        ApplicationProfile() = delete;
        static Windows::Phone::ApplicationModel::ApplicationProfileModes Modes();
    };
}
#endif
