// WARNING: Please don't edit this file. It was generated by C++/WinRT v2.0.190404.8

#ifndef WINRT_Windows_Web_2_H
#define WINRT_Windows_Web_2_H
#include "winrt/impl/Windows.Web.1.h"
namespace winrt::Windows::Web
{
    struct WebError
    {
        WebError() = delete;
        static Windows::Web::WebErrorStatus GetStatus(int32_t hresult);
    };
}
#endif
