// WARNING: Please don't edit this file. It was generated by C++/WinRT v2.0.190404.8

#ifndef WINRT_SDKTemplate_H
#define WINRT_SDKTemplate_H
#include "winrt/base.h"
static_assert(winrt::check_version(CPPWINRT_VERSION, "2.0.190404.8"), "Mismatched C++/WinRT headers.");
#include "winrt/impl/Windows.Foundation.Collections.2.h"
#include "winrt/impl/Windows.UI.Composition.2.h"
#include "winrt/impl/Windows.UI.Xaml.2.h"
#include "winrt/impl/Windows.UI.Xaml.Controls.2.h"
#include "winrt/impl/Windows.UI.Xaml.Interop.2.h"
#include "winrt/impl/Windows.UI.Xaml.Markup.2.h"
#include "winrt/impl/SDKTemplate.2.h"
namespace winrt::impl
{
    template <typename D> void consume_SDKTemplate_IMainPage<D>::NotifyUser(param::hstring const& strMessage, SDKTemplate::NotifyType const& type) const
    {
        check_hresult(WINRT_SHIM(SDKTemplate::IMainPage)->NotifyUser(get_abi(strMessage), get_abi(type)));
    }
    template <typename D> void consume_SDKTemplate_IMainPage<D>::Navigate(Windows::UI::Xaml::Interop::TypeName const& name, Windows::Foundation::IInspectable const& parameter) const
    {
        check_hresult(WINRT_SHIM(SDKTemplate::IMainPage)->Navigate(get_abi(name), get_abi(parameter)));
    }
    template <typename D> hstring consume_SDKTemplate_IMainPageStatics<D>::FEATURE_NAME() const
    {
        void* value{};
        check_hresult(WINRT_SHIM(SDKTemplate::IMainPageStatics)->get_FEATURE_NAME(&value));
        return { value, take_ownership_from_abi };
    }
    template <typename D> Windows::Foundation::Collections::IVector<SDKTemplate::Scenario> consume_SDKTemplate_IMainPageStatics<D>::scenarios() const
    {
        void* value{};
        check_hresult(WINRT_SHIM(SDKTemplate::IMainPageStatics)->get_scenarios(&value));
        return { value, take_ownership_from_abi };
    }
    template <typename D> SDKTemplate::MainPage consume_SDKTemplate_IMainPageStatics<D>::Current() const
    {
        void* value{};
        check_hresult(WINRT_SHIM(SDKTemplate::IMainPageStatics)->get_Current(&value));
        return { value, take_ownership_from_abi };
    }
    template <typename D>
    struct produce<D, SDKTemplate::IMainPage> : produce_base<D, SDKTemplate::IMainPage>
    {
        int32_t WINRT_CALL NotifyUser(void* strMessage, int32_t type) noexcept final try
        {
            typename D::abi_guard guard(this->shim());
            this->shim().NotifyUser(*reinterpret_cast<hstring const*>(&strMessage), *reinterpret_cast<SDKTemplate::NotifyType const*>(&type));
            return 0;
        }
        catch (...) { return to_hresult(); }
        int32_t WINRT_CALL Navigate(struct struct_Windows_UI_Xaml_Interop_TypeName name, void* parameter) noexcept final try
        {
            typename D::abi_guard guard(this->shim());
            this->shim().Navigate(*reinterpret_cast<Windows::UI::Xaml::Interop::TypeName const*>(&name), *reinterpret_cast<Windows::Foundation::IInspectable const*>(&parameter));
            return 0;
        }
        catch (...) { return to_hresult(); }
    };
    template <typename D>
    struct produce<D, SDKTemplate::IMainPageStatics> : produce_base<D, SDKTemplate::IMainPageStatics>
    {
        int32_t WINRT_CALL get_FEATURE_NAME(void** value) noexcept final try
        {
            clear_abi(value);
            typename D::abi_guard guard(this->shim());
            *value = detach_from<hstring>(this->shim().FEATURE_NAME());
            return 0;
        }
        catch (...) { return to_hresult(); }
        int32_t WINRT_CALL get_scenarios(void** value) noexcept final try
        {
            clear_abi(value);
            typename D::abi_guard guard(this->shim());
            *value = detach_from<Windows::Foundation::Collections::IVector<SDKTemplate::Scenario>>(this->shim().scenarios());
            return 0;
        }
        catch (...) { return to_hresult(); }
        int32_t WINRT_CALL get_Current(void** value) noexcept final try
        {
            clear_abi(value);
            typename D::abi_guard guard(this->shim());
            *value = detach_from<SDKTemplate::MainPage>(this->shim().Current());
            return 0;
        }
        catch (...) { return to_hresult(); }
    };
    template <typename D>
    struct produce<D, SDKTemplate::IScenario1_SecondaryWindow> : produce_base<D, SDKTemplate::IScenario1_SecondaryWindow>
    {
    };
    template <typename D>
    struct produce<D, SDKTemplate::IScenario2_DisplayRegion> : produce_base<D, SDKTemplate::IScenario2_DisplayRegion>
    {
    };
    template <typename D>
    struct produce<D, SDKTemplate::IScenario3_Size> : produce_base<D, SDKTemplate::IScenario3_Size>
    {
    };
    template <typename D>
    struct produce<D, SDKTemplate::IScenario4_CompactOverlay> : produce_base<D, SDKTemplate::IScenario4_CompactOverlay>
    {
    };
    template <typename D>
    struct produce<D, SDKTemplate::IScenario5_RelativePositioning> : produce_base<D, SDKTemplate::IScenario5_RelativePositioning>
    {
    };
    template <typename D>
    struct produce<D, SDKTemplate::ISecondaryAppWindowPage> : produce_base<D, SDKTemplate::ISecondaryAppWindowPage>
    {
    };
}
namespace winrt::SDKTemplate
{
}
namespace std
{
    template<> struct hash<winrt::SDKTemplate::IMainPage> : winrt::impl::hash_base<winrt::SDKTemplate::IMainPage> {};
    template<> struct hash<winrt::SDKTemplate::IMainPageStatics> : winrt::impl::hash_base<winrt::SDKTemplate::IMainPageStatics> {};
    template<> struct hash<winrt::SDKTemplate::IScenario1_SecondaryWindow> : winrt::impl::hash_base<winrt::SDKTemplate::IScenario1_SecondaryWindow> {};
    template<> struct hash<winrt::SDKTemplate::IScenario2_DisplayRegion> : winrt::impl::hash_base<winrt::SDKTemplate::IScenario2_DisplayRegion> {};
    template<> struct hash<winrt::SDKTemplate::IScenario3_Size> : winrt::impl::hash_base<winrt::SDKTemplate::IScenario3_Size> {};
    template<> struct hash<winrt::SDKTemplate::IScenario4_CompactOverlay> : winrt::impl::hash_base<winrt::SDKTemplate::IScenario4_CompactOverlay> {};
    template<> struct hash<winrt::SDKTemplate::IScenario5_RelativePositioning> : winrt::impl::hash_base<winrt::SDKTemplate::IScenario5_RelativePositioning> {};
    template<> struct hash<winrt::SDKTemplate::ISecondaryAppWindowPage> : winrt::impl::hash_base<winrt::SDKTemplate::ISecondaryAppWindowPage> {};
    template<> struct hash<winrt::SDKTemplate::MainPage> : winrt::impl::hash_base<winrt::SDKTemplate::MainPage> {};
    template<> struct hash<winrt::SDKTemplate::Scenario1_SecondaryWindow> : winrt::impl::hash_base<winrt::SDKTemplate::Scenario1_SecondaryWindow> {};
    template<> struct hash<winrt::SDKTemplate::Scenario2_DisplayRegion> : winrt::impl::hash_base<winrt::SDKTemplate::Scenario2_DisplayRegion> {};
    template<> struct hash<winrt::SDKTemplate::Scenario3_Size> : winrt::impl::hash_base<winrt::SDKTemplate::Scenario3_Size> {};
    template<> struct hash<winrt::SDKTemplate::Scenario4_CompactOverlay> : winrt::impl::hash_base<winrt::SDKTemplate::Scenario4_CompactOverlay> {};
    template<> struct hash<winrt::SDKTemplate::Scenario5_RelativePositioning> : winrt::impl::hash_base<winrt::SDKTemplate::Scenario5_RelativePositioning> {};
    template<> struct hash<winrt::SDKTemplate::SecondaryAppWindowPage> : winrt::impl::hash_base<winrt::SDKTemplate::SecondaryAppWindowPage> {};
    template<> struct hash<winrt::SDKTemplate::XamlMetaDataProvider> : winrt::impl::hash_base<winrt::SDKTemplate::XamlMetaDataProvider> {};
}
#endif
